### ISSUE TITLE
"initializing workspace" stage doesnt end

### ISSUE THREAD

**Issue by vitalexbel** [peq/wurst4vscode#23]
![screenshot_1](https://user-images.githubusercontent.com/29229748/27603015-63e8ba82-5b7d-11e7-98e9-42a8f74a81fd.png)
When I try to `Clean the wurst workspace`, I get this error>>:
![screenshot_4](https://user-images.githubusercontent.com/29229748/27603133-ce20de34-5b7d-11e7-853f-b4aac59481ec.png)

**Comment by Frotty** [comment]
paste log, as always and for all future tickets.

**Comment by vitalexbel** [comment]
ok

**Comment by vitalexbel** [comment]
```
[Extension Host] Wurst extension activated!!
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Server started 832!
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] setup file logging
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: Exception in thread "main" 
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: 
	at de.peeeq.wurstio.Main.main(Main.java:63)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: 

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] child process exited with code 1
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39)
    at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16)
    at WurstHoverProvider.provideHover (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\features\hoverProvider.js:8:32)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352279
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57373
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:46346)
    at Object.d [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57336)
    at e.provideHover (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352233)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:362450
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

**Comment by Frotty** [comment]
wurst log?

**Comment by vitalexbel** [comment]
only
`2017-06-27 21:48:24 INFO   ### Started wurst version: (1.7.0.0-jenkins-Wurst-340)
`

**Comment by vitalexbel** [comment]
Everything worked fine yesterday.
But after updating Warcraft 3 to 1.28.4 and Wurst to last build, something went wrong.

**Comment by Frotty** [comment]
Oh, why you psot this on wurst4vsecode repo? This is a wurst bug.

**Comment by vitalexbel** [comment]
I read here peq/WurstScript#529 
that VSCode is working
And decided that there are some problem in the vscode on my comp
